# Generated by Django 3.1.7 on 2021-03-15 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Getter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Giver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('activity', models.CharField(max_length=255)),
                ('complex', models.BooleanField(default=False)),
                ('complicated', models.BooleanField(default=False)),
                ('entrustability', models.IntegerField(choices=[(1, 'I did it.'), (2, 'I talked them through it.'), (3, 'I directed them from time to time.'), (4, 'I was available just in case.')], default=1)),
                ('done_well', models.CharField(max_length=255)),
                ('needs_improvement', models.CharField(max_length=255)),
                ('giver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.giver')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
