# Generated by Django 3.1.7 on 2021-03-15 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Getter',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='done_well',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='needs_improvement',
            field=models.TextField(),
        ),
    ]
