# Generated by Django 3.1.7 on 2021-03-15 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_auto_20210315_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='activity',
            field=models.CharField(choices=[('HP', 'History and Physical'), ('PD', 'Prioritize Differential Diagnosis'), ('RI', 'Recommend and Interpret Tests'), ('PH', 'Perform Handover'), ('PP', 'Perform Procedure')], default='HP', max_length=255),
        ),
    ]
